#!/usr/bin/env bash
#| 1 - size binary   (e.g. avr-size)
#| 2 - measurement type (flash or ram)
#| 3 - binary file   (e.g. main.hex)
#| 4 - total available (flash/ram) in bytes
#| 5 - flash/ram text

case "$2" in
"flash")
	USED=$("$1" "$3" | tail -n-1 | awk '{ print $1+$2 }')
	;;
"ram")
	USED=$("$1" "$3" | tail -n-1 | awk '{ print $2+$3 }')
	;;
*)
	echo "INVALID Measurement type: $2"
	exit 1
esac

#  Calculates the total flash/ram used
TOTAL="$4"
PERCENTAGE=$((USED * 100 / TOTAL))

#  Size Colours
if (( PERCENTAGE > 95 )); then
	COLOR="\e[5;31m"
elif (( PERCENTAGE > 90 )); then
	COLOR="\e[31m"
elif (( PERCENTAGE > 80 )); then
	COLOR="\e[38;5;202m"
elif (( PERCENTAGE > 70 )); then
	COLOR="\e[38;5;220m"
elif (( PERCENTAGE > 60 )); then
	COLOR="\e[38;5;154m"
elif (( PERCENTAGE > 50 )); then
	COLOR="\e[33m"
else
	COLOR="\e[32m"
fi

#  Displays Results
NAME="$5"
echo -e " \e[38;5;253m ${NAME}\e[m: ${COLOR}${PERCENTAGE}% \e[m ${USED} / ${TOTAL} B"

exit 0
